name: energized_id_web
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Kai Page <kaibug@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_bloc: ^0.9.0
  http: ^0.12.0

  energized_id:
    git: https://github.com/energized-id/energized_id.git

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  json_serializable: ^3.0.0
  pedantic: ^1.0.0
  sass_builder: ^2.1.3
  test: ^1.5.1
