name: energized_id_web
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Kai Page <kaibug@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_bloc: ^0.9.0
  http: ^0.12.0
  json_annotation: ^2.4.0
  image: ^2.1.4

  # apparently dartdevc does not like git dependencies
  # energized_id:
    # git: https://github.com/energized-id/energized_id.git

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  json_serializable: ^3.0.0
  pedantic: ^1.0.0
  sass_builder: ^2.1.3
